# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
 publish = "dist/"

 # Production context: all deploys from the Production branch set in your site’s
 # deploy contexts will inherit these settings.
 [context.production]
  publish = "dist/"
  command = "npm run build"

 # Branch Deploy context: all deploys that are not from a pull/merge request or
 # from the Production branch will inherit these settings.
 [context.branch-deploy]
 command = "echo branch"

 # The following redirect is intended for use with most SPAs that handle
 # routing internally.
 [[redirects]]
  from = "*"
  to = "/index.html"
  status = 200